### PR TITLE
docs: fix README typo

### PR DESCRIPTION
**Pull request by junk1tm**
Hi there 👋

Great library, I like you style! I've written a similar one (although it's limited to environment variables), maybe we could share some inspiration.

Would you like some assistance with any of the open issues? I'd be happy to help!

### CODE REVIEW

**Review by cristaloleg — DISMISSED** [review]

**Comment by cristaloleg** [comment]
Thank you for kind words. Yeah, I have something to fix, will try to share as much info as possible this weekend so maybe you will pick up something.

**Comment by cristaloleg** [comment]
Will fix docs in 1hr and update your MR, feel free to leave it for now 😉

**Comment by cristaloleg** [comment]
Ah, rebasing via Github UI drops GPG sign, can you manually rebase on the latest `main`, please?

**Comment by junk1tm** [comment]
Sure, will do

**Comment by junk1tm** [comment]
Looks like there is a problem with commit signing on my side, I'll take a look and come back

**Comment by junk1tm** [comment]
Fixed 🎉
Turns out, ssh-agent lost my key for some reason 😅

**Review by cristaloleg — APPROVED** [review]

**Pull request merged**
