### PR TITLE
If FileFlag set and not use, aconfig override Files with empty string 

### PR DESCRIPTION
**Pull request by mef13**
Config example:
```
aconfig.Config{
		SkipFiles:          false,
		SkipFlags:          false,
		FailOnFileNotFound: true,
		MergeFiles:         false,
		FileFlag:           "cfg",
		Files:              []string{"conf/settings.yaml"},
```

if run binary without -cfg flag,  Files become  []string{""}

### CODE REVIEW

**Review by cristaloleg — APPROVED** [review]
thanks

**Comment by cristaloleg** [comment]
Before clicking `Merge` I've asked myself: should we return an error on empty `FileFlag` ? for me it sounds pretty ok, if `FileFlag` is set to `-config` and it's empty what it does mean at all?

**Comment by mef13** [comment]
> Before clicking `Merge` I've asked myself: should we return an error on empty `FileFlag` ? for me it sounds pretty ok, if `FileFlag` is set to `-config` and it's empty what it does mean at all?

I think no. If you configure EnvPrefix or FlagPrefix this does'n mean that you necessarily want env or flag. This only makes it possible to use them. 
If programmer wants necessarily uses FileFlag, he can use config with empty string in Files slice:
```
aconfig.Config{
		SkipFiles:          false,
		SkipFlags:          false,
		FailOnFileNotFound: true,
		MergeFiles:         false,
		FileFlag:           "cfg",
		Files:              []string{""},
```
and get error "The system cannot find the path specified." when flag not defined.

**Comment by cristaloleg** [comment]
Fixed in #73

**Pull request closed without merging**
